# Generated by Django 5.2.4 on 2025-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_examenes', '0002_alter_doctor_user_alter_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
