# Generated by Django 5.2.4 on 2025-07-21 02:23

import api_examenes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_examenes', '0003_alter_paciente_altura_alter_paciente_peso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenrealizado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='examenrealizado',
            name='imagenes_diagnosticas',
        ),
        migrations.AddField(
            model_name='examenrealizado',
            name='video_diagnostico',
            field=models.FileField(blank=True, null=True, upload_to=api_examenes.models.ruta_video_diagnostico),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examenrealizado',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_examenes.cita'),
        ),
    ]
